//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyWorldProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDelivery1
    {
        public int DeliveryID { get; set; }
        public int CustomerID { get; set; }
        public string PersonName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Landmark { get; set; }
        public int Pincode { get; set; }
        public string Type { get; set; }
    }
}
